-- Run these commands in your Supabase SQL Editor to enable the Contacts and Memories features

-- 1. Create Contacts Table
create table contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text not null,
  email text,
  social text
);

-- Enable RLS for Contacts
alter table contacts enable row level security;

-- Policies for Contacts
create policy "Public Read Contacts" 
on contacts for select 
using (true);

create policy "Public Insert Contacts" 
on contacts for insert 
with check (true);

create policy "Public Delete Contacts" 
on contacts for delete 
using (true);

-- 2. Create Memories Table
create table memories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null,
  author text
);

-- Enable RLS for Memories
alter table memories enable row level security;

-- Policies for Memories
create policy "Public Read Memories" 
on memories for select 
using (true);

create policy "Public Insert Memories" 
on memories for insert 
with check (true);

create policy "Public Delete Memories" 
on memories for delete 
using (true);
