import React from 'react';
import { useLanguage } from '../contexts/LanguageContext';
import { Code, Server, Database, Layers } from 'lucide-react';

const Guide: React.FC = () => {
  const { t } = useLanguage();

  const steps = [
    {
      title: t('guide.step1'),
      desc: t('guide.step1.desc'),
      icon: Code,
      color: 'text-blue-600 bg-blue-100',
    },
    {
      title: t('guide.step2'),
      desc: t('guide.step2.desc'),
      icon: Server,
      color: 'text-green-600 bg-green-100',
    },
    {
      title: t('guide.step3'),
      desc: 'Connect to Supabase for persistent data storage.',
      icon: Database,
      color: 'text-purple-600 bg-purple-100',
    },
  ];

  return (
    <div className="bg-gray-50 min-h-screen py-12">
      <div className="max-w-4xl mx-auto px-4">
        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
          <div className="bg-primary p-8 text-white">
            <h1 className="font-serif text-3xl font-bold mb-2">{t('guide.title')}</h1>
            <p className="text-blue-100">{t('guide.intro')}</p>
          </div>
          
          <div className="p-8">
            <div className="space-y-12">
                {steps.map((step, idx) => (
                    <div key={idx} className="flex gap-6">
                        <div className={`shrink-0 w-12 h-12 rounded-xl flex items-center justify-center ${step.color}`}>
                            <step.icon size={24} />
                        </div>
                        <div>
                            <h3 className="text-xl font-bold text-gray-900 mb-2">{step.title}</h3>
                            <p className="text-gray-600 leading-relaxed">{step.desc}</p>
                        </div>
                    </div>
                ))}
            </div>

            {/* Supabase Setup Guide */}
            <div className="mt-12 p-6 bg-gray-50 rounded-xl border border-dashed border-gray-300">
                <div className="flex items-center gap-2 mb-4 text-gray-900 font-bold">
                    <Database size={20} />
                    <span>Supabase Setup Instructions</span>
                </div>
                
                <div className="space-y-4">
                  <div>
                    <h4 className="font-semibold text-sm mb-2">1. Create Table (SQL Editor)</h4>
                    <pre className="text-xs md:text-sm bg-gray-900 text-gray-300 p-4 rounded-lg overflow-x-auto">
{`create table guestbook_messages (
  id bigint generated by default as identity primary key,
  author text not null,
  content text not null,
  avatar_color text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);`}
                    </pre>
                  </div>

                  <div>
                    <h4 className="font-semibold text-sm mb-2">2. Environment Variables (.env.local)</h4>
                    <p className="text-sm text-gray-600 mb-2">Add the following keys from your Supabase Project Settings:</p>
                    <pre className="text-xs md:text-sm bg-gray-900 text-gray-300 p-4 rounded-lg overflow-x-auto">
{`SUPABASE_URL=https://your-project.supabase.co
SUPABASE_ANON_KEY=your-anon-key-here`}
                    </pre>
                  </div>
                </div>
            </div>

            <div className="mt-8 p-6 bg-gray-50 rounded-xl border border-dashed border-gray-300">
                <div className="flex items-center gap-2 mb-4 text-gray-900 font-bold">
                    <Layers size={20} />
                    <span>Project Structure</span>
                </div>
                <pre className="text-xs md:text-sm bg-gray-900 text-gray-300 p-4 rounded-lg overflow-x-auto">
{`src/
  ├── components/    # Reusable UI (Layout, Navbar)
  ├── constants/     # Translations & Config
  ├── contexts/      # State Management (Language)
  ├── pages/         # Page Views
  ├── services/      # API Logic (Gemini AI, Supabase)
  └── App.tsx        # Routing`}
                </pre>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Guide;